"""Regenerate manuscript tables from the version-separated evidence summaries.

Run from any directory with Python 3.10+. No third-party packages are needed.
Raw evidence is never modified. SHA256 values bind each consumed summary.
"""
from __future__ import annotations

import csv
import hashlib
import json
import statistics
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE.parent / "paper-data"
OUT = HERE / "tables"
INPUTS: dict[str, str] = {}


def read_bytes(relative: str) -> bytes:
    value = (DATA / relative).read_bytes()
    INPUTS[relative] = hashlib.sha256(value).hexdigest()
    return value


def read_json(relative: str):
    return json.loads(read_bytes(relative).decode("utf-8-sig"))


def read_csv(relative: str):
    return list(csv.DictReader(read_bytes(relative).decode("utf-8-sig").splitlines()))


def table(name: str, spec: str, headers: list[str], rows: list[list[str]]):
    text = ["% Generated by generate_tables.py; do not edit by hand.",
            rf"\begin{{tabular}}{{{spec}}}", r"\toprule",
            " & ".join(headers) + r" \\", r"\midrule"]
    text += [" & ".join(row) + r" \\" for row in rows]
    text += [r"\bottomrule", r"\end{tabular}", ""]
    (OUT / name).write_text("\n".join(text), encoding="ascii")


def main():
    OUT.mkdir(exist_ok=True)
    abstract = (HERE / "abstract.txt").read_text(encoding="ascii").strip()
    assert len(abstract) <= 1920
    (HERE / "abstract-body.tex").write_text(abstract.replace("%", r"\%") + "\n", encoding="ascii")
    current = read_json("20260916-followup/analysis-followup.json")
    assert not current["failedRecords"], current["failedRecords"]
    modes = [
        ("off", "Off"),
        ("resident", "Ordinary resident"),
        ("resident-nested-fullsnapshot", "Nested, full snapshot"),
        ("resident-nested-hidehv", "Nested, sparse snapshot"),
        ("resident-vmread256", r"Ordinary + 256 VMREADs"),
        ("resident-vmread512", r"Ordinary + 512 VMREADs"),
    ]
    a = {(r["condition"], r["workload"]): r for r in current["attribution"]}
    rows = []
    for mode, label in modes:
        c, p = a[mode, "cpuid"], a[mode, "ping"]
        assert c["n"] == p["n"] == 5
        cs, ps = c["nsPerOperation"], p["nsPerOperation"]
        rows.append([label, f'{cs["median"] / 1000:.3f}',
                     f'{cs["min"] / 1000:.3f}--{cs["max"] / 1000:.3f}',
                     f'{ps["median"] / 1000:.3f}',
                     f'{ps["min"] / 1000:.3f}--{ps["max"] / 1000:.3f}'])
    table("attribution.tex", "@{}lrrrr@{}",
          ["Mode", r"CPUID (\us)", "Min--max", r"RTT (\us)", "Min--max"], rows)

    lat = {r["condition"]: r for r in current["latency"]}
    latency_runs = read_csv("20260916-followup/latency-runs.csv")
    assert len(latency_runs) == 24
    response_count = sum(int(r["requests"]) for r in latency_runs)
    assert response_count == 74145
    transition_times = {}
    for condition in ["insert", "remove"]:
        runs = [r for r in latency_runs if r["condition"] == condition and r["warmup"] == "False"]
        assert len(runs) == 5
        transition_times[condition] = {
            metric: {"median": statistics.median(float(r[metric]) for r in runs),
                     "max": max(float(r[metric]) for r in runs)}
            for metric in ["driverCommandUs", "rendezvousUs"]}
    rows = []
    for mode, label in [("sham-off", "Sham, off"), ("insert", "Insert"),
                        ("sham-on", "Sham, on"), ("remove", "Remove")]:
        r = lat[mode]
        assert r["n"] == 5
        rows.append([label, f'{r["rttP99Us"]["median"]:.2f}',
                     f'{r["commandOverlapGapMaxUs"]["median"] / 1000:.4f}',
                     f'{r["commandOverlapGapMaxUs"]["max"] / 1000:.4f}',
                     f'{r["commandDurationMs"]["median"]:.2f}'])
    table("latency.tex", "@{}lrrrr@{}",
          ["Condition", r"p99 RTT (\us)", "Gap median (ms)", "Gap max (ms)", "Call (ms)"], rows)

    life = read_json("20260916-followup/lifecycle/derived/smp-summary.json")
    assert life["cycles"]["idle:remap-restore:pass"] == 3
    assert sum(life["faults"].values()) == 15 and not life["incomplete"]
    rows = []
    for key, label in [("mapBodyUs", "Map body"), ("restoreBodyUs", "Restore body"),
                       ("commitDrainUs", "Commit drain"), ("retireDrainUs", "Retirement drain")]:
        r = life["latencyUs"]["idle"][key]
        rows.append([label, str(r["n"]), f'{r["median"]:.1f}', f'{r["min"]:.1f}', f'{r["max"]:.1f}'])
    table("lifecycle.tex", "@{}lrrrr@{}",
          ["Boundary", "$n$", r"Median (\us)", r"Min (\us)", r"Max (\us)"], rows)

    nested = read_csv("20260915-4x2/derived/nested-improvements.csv")
    labels = {"cpu": "Integer loop", "cpuid": "CPUID", "latency": "Pointer chase",
              "memory": "Memory copy (2 GiB)", "net": "TCP bulk", "ping": "TCP RTT"}
    rows = []
    for r in nested:
        old = f'{float(r["beforeSeconds"]):.6f}' if r["beforeSeconds"] else "3/3 timeouts"
        delta = f'{-float(r["elapsedReductionPercent"]):+.2f}\\%' if r["elapsedReductionPercent"] else "Not estimated"
        rows.append([labels[r["workload"]], old, f'{float(r["afterSeconds"]):.6f}', delta])
    table("historical-nested.tex", "@{}lrrr@{}",
          ["Workload", "Earlier (s)", "Optimized (s)", "Elapsed change"], rows)

    win = read_csv("20260915-4x2/after/derived/windows-overhead.csv")
    labels = {"cpuid-leaf0": "CPUID leaf 0", "disk-direct-read-64MiB": "Direct disk read",
              "disk-direct-write-64MiB": "Direct disk write", "integer-xorshift": "Integer loop",
              "memcpy-32MiB": "Memory copy", "pointer-chase-64MiB": "Pointer chase",
              "tcp-loopback-64MiB": "TCP bulk", "tcp-loopback-rtt-1B": "TCP RTT"}
    rows = [[labels[r["workload"]], f'{float(r["elapsedOverheadPercent"]):+.2f}\\%',
             f'{float(r["bootstrap95LowPercent"]):+.2f}\\% to {float(r["bootstrap95HighPercent"]):+.2f}\\%'] for r in win]
    table("historical-windows.tex", "@{}lrr@{}",
          ["Workload", "Elapsed overhead", "Bootstrap 95\\% interval"], rows)

    app = read_json("20260916-followup/application/derived/http-page-summary.json")
    policy = read_json("20260916-followup/application/derived/policy-comparison.json")
    complete = [r for r in app["runs"] if r["result"] == "pass"]
    assert len(complete) == 3 and len(app["runs"]) == 4
    assert sum(sum(r["responses"].values()) for r in complete) == 90
    assert all(r["independentHolderLiveness"] is False for r in complete)
    assert len(policy["inplace"]) == 3
    assert all(r["result"] == "pass" for r in policy["inplace"])
    assert sum(s["count"] for r in policy["inplace"] for s in r["stages"].values()) == 78
    assert sum(s.get("settlingWindowExcluded", 0) for r in policy["inplace"] for s in r["stages"].values()) == 6
    rows = [[r["runId"].replace("http-page-20260916T", "").replace("Z", ""),
             r["result"], str(sum(r.get("responses", {}).values())) if r["result"] == "pass" else "Incomplete",
             f'{r["maxPfnSampleAgeSeconds"]:.3f}' if r["result"] == "pass" else "--"] for r in app["runs"]]
    table("application-runs.tex", "@{}llrr@{}",
          ["Run suffix (UTC)", "Outcome", "Strict responses", "Max PFN age (s)"], rows)

    cpuid_ratio = a["resident-nested-hidehv", "cpuid"]["nsPerOperation"]["median"] / a["off", "cpuid"]["nsPerOperation"]["median"]
    rtt_overhead = (a["resident-nested-hidehv", "ping"]["nsPerOperation"]["median"] / a["off", "ping"]["nsPerOperation"]["median"] - 1) * 100
    manifest = {"inputs": INPUTS, "derivedClaims": {"cpuidRatio": cpuid_ratio,
                "tcpRttOverheadPercent": rtt_overhead, "completeEptApplicationTrials": len(complete),
                "pacedTcpResponses": response_count, "transitionTimesUs": transition_times,
                "metadataAbstractCharacters": len(abstract)},
                "note": "Inputs are derived evidence summaries, whose raw inputs are indexed in their datasets. Cohorts are not pooled."}
    (HERE / "table-provenance.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Generated 6 tables from {len(INPUTS)} evidence summaries; CPUID={cpuid_ratio:.4f}x, RTT={rtt_overhead:.4f}%")


if __name__ == "__main__":
    main()
